name: Deploy CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # O la versión que uses

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas
        run: npm test  # Reemplázalo con tu comando de pruebas

      - name: Construir el proyecto
        run: npm run build  # Reemplázalo si tienes un script diferente

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Desplegar a GitHub Pages
        if: success()
        run: npm run deploy  # Si tu proyecto usa GitHub Pages, cambia esto según tu configuración

      - name: Mensaje final
        run: echo "Despliegue completado con éxito."
